language: node_js
node_js:
    - 'stable'
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
before_script:
  - psql -c 'create database storemanager;' -U postgres
script:
    - npm test
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
