version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: d2e3c8a68a37b7d71ce3f4bb067fd2ae784fb47d2d7be162d853d5b790e15df1
    docker:
      - image: circleci/node:8
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: forsetti
            POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Wait for postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # run tests!
      - run:
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?